vote:
  image: zavrelmi/vote:master
  ports:
    - 5005:80

redis:
  image: redis:alpine

db:
  image: postgres:9.4

result:
  image: zavrelmi/result:master
  ports:
    - 5055:4000

worker:
  image: zavrelmi/worker:latest
